version: '3'
services:
  nginx:
    build:
      context: ./docker/
      dockerfile: server.docker
    volumes:
      - ./:/var/www
    ports:
      - '${APP_PORT}:80'
  php:
    build:
      context: ./docker/
      dockerfile: app.docker
    volumes:
      - ./:/var/www
  db:
    image: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - '${DB_PORT}:5432'
